name: Build QA Model Worker
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
      name: CI
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bothubit/bothub-nlp:${{ steps.vars.outputs.tag }}-QA
          no-cache: true
          build-args: |
            DOWNLOAD_MODEL_URL=${{ secrets.URL_PT_BR_MODEL }}|${{ secrets.URL_EN_MODEL }}|${{ secrets.URL_MULTILANG_MODEL }}
